<?php
/* @var $this Magneto_Varnish_Block_Adminhtml_Purge */
?>

<br/>
<div class="content-header">
	<table cellspacing="0">
		<tr>
			<td><h3><?php echo Mage::helper('adminhtml')->__('Purge Urls from Varnish') ?></h3></td>
		</tr>
	</table>
</div>

<form action="<?php echo $this->getUrl('*/*/purgeUrls') ?>" method="post">

	<table class="form-list">
		<tbody>
		<tr>
			<td>
				<textarea rows="2" cols="100" name="purge_urls"></textarea>
			</td>
		</tr>
		<tr>
			<td>
				<input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>" />
				<button type="submit"><?php echo $this->__('Purge Urls') ?></button>
			</td>
		</tr>
		</tbody>
	</table>

</form>